# Generated by Django 4.1.1 on 2022-09-19 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_jobs_delete_doctors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='job_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.departments'),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='salary',
            field=models.CharField(max_length=255),
        ),
    ]
