# Generated by Django 4.1.1 on 2022-09-23 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_jobs_job_category_alter_jobs_salary'),
    ]

    operations = [
        migrations.CreateModel(
            name='login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_name', models.CharField(max_length=255)),
                ('Last_name', models.CharField(max_length=255)),
                ('Email_address', models.EmailField(max_length=254)),
                ('Password', models.CharField(max_length=50)),
                ('logged_on', models.DateField(auto_now=True)),
            ],
        ),
    ]
