# Generated by Django 4.1.1 on 2022-09-24 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_login_applied_on'),
    ]

    operations = [
        migrations.RenameField(
            model_name='login',
            old_name='applied_on',
            new_name='Applied_on',
        ),
    ]
