# Generated by Django 4.1.1 on 2022-09-24 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_rename_applied_on_login_applied_on'),
    ]

    operations = [
        migrations.RenameField(
            model_name='login',
            old_name='Applied_on',
            new_name='Logged_on',
        ),
    ]
